export default {
  type: "FeatureCollection",
  crs: {
    type: "name",
    properties: { name: "urn:ogc:def:crs:OGC:1.3:CRS84" },
  },
  features: [
    {
      type: "Feature",
      properties: {
        PARK_ID: 960,
        FACILITYID: 28014,
        NAME: "Bearbrook Skateboard Park",
        NAME_FR: "Planchodrome Bearbrook",
        ADDRESS: "8720 Russell Road",
        ADDRESS_FR: "8720, chemin Russell",
        FACILITY_T: "flat",
        FACILITY_1: "plat",
        ACCESSCTRL: "no/non",
        ACCESSIBLE: "no/non",
        OPEN: null,
        NOTES: "Outdoor",
        MODIFIED_D: "2018/01/18",
        CREATED_DA: null,
        FACILITY:
          "Neighbourhood : smaller size facility to service population of 10,000 or less",
        FACILITY_F:
          "De voisinage : petite installation assurant des services à 10 000 résidents ou moins.",
        DESCRIPTIO: "Flat asphalt surface, 5 components",
        DESCRIPT_1: "Surface d'asphalte plane, 5 modules",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-75.3372987731628, 45.383321536272049],
      },
    },
    {
      type: "Feature",
      properties: {
        PARK_ID: 1219,
        FACILITYID: 28001,
        NAME: "Bob MacQuarrie Skateboard Park (SK8 Extreme Park)",
        NAME_FR: "Planchodrome Bob-MacQuarrie (Parc SK8 Extreme)",
        ADDRESS: "1490 Youville Drive",
        ADDRESS_FR: "1490, promenade Youville",
        FACILITY_T: "other",
        FACILITY_1: "autre",
        ACCESSCTRL: "no/non",
        ACCESSIBLE: "no/non",
        OPEN: null,
        NOTES: "Outdoor",
        MODIFIED_D: "2018/01/18",
        CREATED_DA: null,
        FACILITY:
          "Community: mid size facility to service population of 40,000 plus",
        FACILITY_F:
          "Communautaire : installation de taille moyenne assurant des services à 40 000 résidents ou plus.",
        DESCRIPTIO:
          "Flat asphalt surface, 10 components, City run learn to skateboard programs, City run skateboard camps in summer",
        DESCRIPT_1:
          "Surface d'asphalte plane, 10 modules, programmes et camps de planche à roulettes en été géré par la Ville",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-75.546518086577947, 45.467134581917357],
      },
    },
    {
      type: "Feature",
      properties: {
        PARK_ID: 1157,
        FACILITYID: 28002,
        NAME: "Walter Baker Skateboard Park",
        NAME_FR: "Planchodrome Walter-Baker",
        ADDRESS: "100 Charlie Rogers Place",
        ADDRESS_FR: "100, place Charlie Rogers",
        FACILITY_T: "bowl",
        FACILITY_1: "bol",
        ACCESSCTRL: "no/non",
        ACCESSIBLE: "no/non",
        OPEN: null,
        NOTES: "Outdoor",
        MODIFIED_D: "2018/01/18",
        CREATED_DA: null,
        FACILITY:
          "Community : mid size facility to service population of 40,000 plus",
        FACILITY_F:
          "Communautaire : installation de taille moyenne assurant des services à 40 000 résidents ou plus.",
        DESCRIPTIO: "Concrete bowl, 7,000 sq ft",
        DESCRIPT_1: "Bol de béton, 7 000 pi2",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-75.898610599532319, 45.295014379864874],
      },
    },
    {
      type: "Feature",
      properties: {
        PARK_ID: 9,
        FACILITYID: 28006,
        NAME: "Roving Skateboard Park Location",
        NAME_FR: "Lieu de planchodrome itinérant",
        ADDRESS: "2785 8th Line Road",
        ADDRESS_FR: "2785, chemin 8th Line",
        FACILITY_T: "other",
        FACILITY_1: "autre",
        ACCESSCTRL: "no/non",
        ACCESSIBLE: "no/non",
        OPEN: null,
        NOTES: "Outdoor - Mobile",
        MODIFIED_D: "2018/01/18",
        CREATED_DA: null,
        FACILITY: "Metcalfe Community Centre - Roving Skateboard Park Location",
        FACILITY_F:
          "Centre communautaire de Metcalfe - Lieu de planchodrome itinérant",
        DESCRIPTIO: "Flat surface, 5 components",
        DESCRIPT_1: "Surface plane, 5 modules",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-75.468561642270757, 45.23032561834377],
      },
    },
    {
      type: "Feature",
      properties: {
        PARK_ID: 1160,
        FACILITYID: 28007,
        NAME: "Roving Skateboard Park Location",
        NAME_FR: "Lieu de planchodrome itinérant",
        ADDRESS: "10 Warner Colpitts Lane",
        ADDRESS_FR: "10, ruelle Warner Colpitts",
        FACILITY_T: "flat",
        FACILITY_1: "plat",
        ACCESSCTRL: "yes/oui",
        ACCESSIBLE: "no/non",
        OPEN: null,
        NOTES: "Indoor - Summer",
        MODIFIED_D: "2018/03/07",
        CREATED_DA: null,
        FACILITY:
          "Johnny Leroux Stittsville Community Arena - Roving Skateboard Park Location",
        FACILITY_F:
          "Aréna communautaire de Stittsville Johnny-Leroux - Lieu de planchodrome itinérant",
        DESCRIPTIO: "Flat surface, 5 components",
        DESCRIPT_1: "Surface plane, 5 modules",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-75.926651366520872, 45.260659774950561],
      },
    },
    {
      type: "Feature",
      properties: {
        PARK_ID: 1693,
        FACILITYID: 28016,
        NAME: "Legacy Skateboard Park",
        NAME_FR: "Planchodrome Legacy",
        ADDRESS: "101 Centrepointe Drive",
        ADDRESS_FR: "101, promenade Centrepointe",
        FACILITY_T: "bowl",
        FACILITY_1: "bol",
        ACCESSCTRL: "no/non",
        ACCESSIBLE: "no/non",
        OPEN: null,
        NOTES: "Outdoor",
        MODIFIED_D: "2018/01/18",
        CREATED_DA: null,
        FACILITY:
          "District: larger facility to service population of 100,000 plus",
        FACILITY_F:
          "De district : grande installation assurant des services à 100 000 résidents ou plus.",
        DESCRIPTIO:
          "Large concrete bowl, many street and vertical components, 17,000 sq ft",
        DESCRIPT_1:
          "Grand bol de béton, modules de rue et modules verticaux, 17 000 pi2",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-75.760933332842754, 45.345566668964558],
      },
    },

    {
      type: "Feature",
      properties: {
        PARK_ID: 1133,
        FACILITYID: 28020,
        NAME: "Roving Skateboard Park Location",
        NAME_FR: "Lieu de planchodrome itinérant",
        ADDRESS: "100 Clifford Campbell Street",
        ADDRESS_FR: "100, rue Clifford-Campbell",
        FACILITY_T: "flat",
        FACILITY_1: "plat",
        ACCESSCTRL: "no/non",
        ACCESSIBLE: "no/non",
        OPEN: null,
        NOTES: "Outdoor",
        MODIFIED_D: "2018/01/18",
        CREATED_DA: null,
        FACILITY:
          "Fitzroy Harbour Community Centre - Roving Skateboard Park Location",
        FACILITY_F:
          "Centre communautaire de Fitzroy Harbour - Lieu de planchodrome itinérant",
        DESCRIPTIO: "Flat surface, 5 components",
        DESCRIPT_1: "Surface plane, 5 modules",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-76.206087708136721, 45.470459866077654],
      },
    },

    {
      type: "Feature",
      properties: {
        PARK_ID: 812,
        FACILITYID: 35050,
        NAME: "Charlie Bowins Skateboard Park",
        NAME_FR: "Planchodrome Charlie-Bowins",
        ADDRESS: "435 Bronson Avenue",
        ADDRESS_FR: "435, avenue Bronson",
        FACILITY_T: "bowl",
        FACILITY_1: "bol",
        ACCESSCTRL: "no/non",
        ACCESSIBLE: "no/non",
        OPEN: null,
        NOTES:
          "Outdoor (Commemoratively named Charlie Bowins Skateboard Park on June 10, 2015)",
        MODIFIED_D: "2018/01/18",
        CREATED_DA: "2015/05/20",
        FACILITY:
          "District: larger facility to service population of 100,000 plus",
        FACILITY_F:
          "De district : grande installation assurant des services à 100 000 résidents ou plus.",
        DESCRIPTIO:
          "Flat concrete surface, 10 plus components (large half pipe), City run learn to skateboard programs, City run skateboard camps in summer",
        DESCRIPT_1:
          "Surface de béton plane, 10 modules ou plus (grande demi-lune), programmes et camps de planche à roulettes en été géré par la Ville",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-75.703622500360268, 45.408488357092367],
      },
    },
    {
      type: "Feature",
      properties: {
        PARK_ID: 2457,
        FACILITYID: 35637,
        NAME: "Diamond Jubilee Skateboard Park",
        NAME_FR: "Planchodrome Jubilé de Diamant",
        ADDRESS: "2810 Findlay Creek Drive",
        ADDRESS_FR: "2810, promenade Findlay Creek",
        FACILITY_T: "flat",
        FACILITY_1: "plat",
        ACCESSCTRL: "no/non",
        ACCESSIBLE: "yes/oui",
        OPEN: null,
        NOTES: "Outdoor",
        MODIFIED_D: "2017/07/11",
        CREATED_DA: "2016/06/22",
        FACILITY:
          "Neighbourhood : smaller size facility to service population of 10,000 or less",
        FACILITY_F:
          "De voisinage : petite installation assurant des services à 10 000 résidents ou moins.",
        DESCRIPTIO: "Flat asphalt surface, 5 components",
        DESCRIPT_1: "Surface d'asphalte plane, 5 modules",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-75.609516309730921, 45.314086718258636],
      },
    },

    {
      type: "Feature",
      properties: {
        PARK_ID: 2488,
        FACILITYID: 35815,
        NAME: "Greely Village Skateboard Park",
        NAME_FR: "Planchodrome Greely Village",
        ADDRESS: "7292 Parkway Road",
        ADDRESS_FR: "7292, chemin Parkway",
        FACILITY_T: "other",
        FACILITY_1: "autre",
        ACCESSCTRL: "no/non",
        ACCESSIBLE: "yes/oui",
        OPEN: null,
        NOTES: "Outdoor",
        MODIFIED_D: "2018/01/04",
        CREATED_DA: "2017/04/28",
        FACILITY:
          "Neighbourhood : smaller size facility to service population of 10,000 or less",
        FACILITY_F:
          "De voisinage : petite installation assurant des services à 10 000 résidents ou moins.",
        DESCRIPTIO: "Flat concrete surface, 5 components",
        DESCRIPT_1: "Surface de béton plane, 5 modules",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-75.553065849890629, 45.265433081236672],
      },
    },
    {
      type: "Feature",
      properties: {
        PARK_ID: 330,
        FACILITYID: 28003,
        NAME: "Manotick Skateboard Park",
        NAME_FR: "Planchodrome Manotick",
        ADDRESS: "5572 Doctor Leach Drive",
        ADDRESS_FR: "5572, promenade Doctor-Leach",
        FACILITY_T: "flat",
        FACILITY_1: "plat",
        ACCESSCTRL: "yes/oui",
        ACCESSIBLE: "no/non",
        OPEN: null,
        NOTES: "Outdoor - Joined with basketball",
        MODIFIED_D: "2018/01/18",
        CREATED_DA: null,
        FACILITY:
          "Community: mid size facility to service population of 40,000 plus",
        FACILITY_F:
          "Communautaire : installation de taille moyenne assurant des services à 40 000 résidents ou plus.",
        DESCRIPTIO: "Flat asphalt surface, 8 components",
        DESCRIPT_1: "Surface d'asphalte plane, 8 modules",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-75.686746214582783, 45.22266136322127],
      },
    },

    {
      type: "Feature",
      properties: {
        PARK_ID: 2278,
        FACILITYID: 49211,
        NAME: "Vista Skateboard Park",
        NAME_FR: "Planchodrome Vista",
        ADDRESS: "720 Vistapark Drive",
        ADDRESS_FR: "720, promenade Vistapark",
        FACILITY_T: "flat",
        FACILITY_1: "plat",
        ACCESSCTRL: "no/non",
        ACCESSIBLE: "yes/oui",
        OPEN: null,
        NOTES: "Outdoor",
        MODIFIED_D: "2018/11/29",
        CREATED_DA: "2018/06/22",
        FACILITY:
          "Neighbourhood : smaller size facility to service population of 10,000 or less",
        FACILITY_F:
          "De voisinage : petite installation assurant des services à 10 000 résidents ou moins.",
        DESCRIPTIO: "Flat surface, 5 components",
        DESCRIPT_1: "Surface plane, 5 modules",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-75.471003922143311, 45.450391044010431],
      },
    },
    {
      type: "Feature",
      properties: {
        PARK_ID: 2113,
        FACILITYID: 35299,
        NAME: "Innovation Skateboard Park",
        NAME_FR: "Planchomdrome Innovation",
        ADDRESS: "4101 Innovation Drive",
        ADDRESS_FR: "4101, promenade Innovation",
        FACILITY_T: "bowl",
        FACILITY_1: "bol",
        ACCESSCTRL: "no/non",
        ACCESSIBLE: "yes/oui",
        OPEN: null,
        NOTES: "Outdoor",
        MODIFIED_D: "2017/07/11",
        CREATED_DA: "2016/02/08",
        FACILITY:
          "District: larger facility to service population of 100,000 plus",
        FACILITY_F:
          "De district : grande installation assurant des services à 100 000 résidents ou plus.",
        DESCRIPTIO:
          "Large concrete bowl, 10 plus components, many street and vertical components",
        DESCRIPT_1:
          "Grand bol de béton, 10 modules ou plus, modules de rue et modules verticaux",
        PICTURE_LI: null,
        PICTURE_DE: null,
        PICTURE__1: null,
      },
      geometry: {
        type: "Point",
        coordinates: [-75.931122879767898, 45.34125624499935],
      },
    },
  ],
};
